# Site settings
title: CIO.gov
description: Official Web Site of CIO.gov
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.cio.gov" # the base hostname & protocol for your site
logo: /assets/img/logo-main.png
iconenvelope: /assets/img/iconenvelope.png
iconpaper: /assets/img/iconpaper.png
feature_image: /assets/img/feature-background.jpg
org_name: CIO.gov
repo_name: federalist-modern-team-template

colors:
  background: '#ffffff'
  link:
    color: '#0071bc'
    active: '#0071bc'
    hover: '#205493'
    visited: '#0071bc'
  button:
    background: '#0071bc'
    hover: '#205493'
    text: '#fff'
  headers: '#205493'
  text: '#212121'
  reverse_text: '#ffffff'
  projects:
    accent: '#02bfe7'
    card-heading: '#0071bc'
  banner:
    background: '#112e51'
    text: '#fff'
    button:
      background: '#dce4ef'
      text: '#112e51'
  footer:
    primary-background: '#363f48'
    secondary-background: '#d6d7d9'
    text: '#ffffff'

analytics:
  google:
    code: 'UA-48605964-32' # Change this to your GSA analytics code
  dap:
    agency: CIO    # Change this to your agency
    subagency: CIO.gov # Change this to your agency

defaults:
  scope:
    path: "_tags" # an empty string here means all files in the project
  values:
    layout:
      - tag_index


forms:
- type: newsletter
  heading: Sign up to receive updates from our team
  url: https://docs.google.com/forms/d/1Tsdm_2spbxWnmTFMrH5eHxpOAN9W4LB3eaMMXJ1N0rU/formResponse
  button: Subscribe
  privacypolicy: Your privacy and security are important to us, we'll only share your information as described in the <a href="http://www.gsa.gov/portal/content/116609">GSA Privacy and Security Notice</a>
  fields:
    - type: email
      name: entry.1440502332
      label: Email Address
    - type: hidden
      name: fbzx
      value: -7861934959779167198

footer:
  links:
      - text: About
        permalink: /about/
      - text: Agenda
        permalink: /cioc-priorities/
      - text: Blog
        permalink: /blog/
      - text: Reources
        permalink: /resources/


  image: /assets/img/CIO-council-Logo-silver1.png
  contact:
    name: CIO Council
    email: feedback@cio.gov
    twitter:
      - ciodotgov
  text:
 # Change to a tag line for your agency

# Build settings
markdown: kramdown
include:
  - _navigation.json
exclude:
  - CONTRIBUTING.md
  - LICENSE.md
  - README.md

# Inititalize project and team collections
collections:
  blogs:
    output: true
  priorities:
    output: true
  initiatives:
    output: true
  pastinitiatives:
    output: true
  resources:
    output: true
  members:
    output: true
  leadership:
    output: true

plugins_dir:
  - jekyll-paginate-v2
  - jekyll-feed

pagination:
  paginate_path: /blog/page:num/
  enabled: true
  per_page: 5
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

wds-version: 1.1.0
